### PR TITLE
ugettex_lazzy -> gettext_lazzy

### PR DESCRIPTION
**Pull request by kocunop**
fix django 4.0 support
ugettext_lazzy is depricated.

### CODE REVIEW

**Comment by kocunop** [comment]
This patch drop support django < 2.2

**Comment by sebatyler** [comment]
Thanks for this PR. I've checked old django versions and 1.8 has gettext_lazy.
I'm not sure that 1.7 or lower verions have it but at least 1.8 and upper versions have it.

**Comment by sebatyler** [comment]
https://docs.djangoproject.com/en/1.8/ref/utils/#django.utils.translation.gettext_lazy

**Comment by sebatyler** [comment]
I've just released the new version including this.
https://pypi.org/project/django-user-activity-log2/0.0.25/

**Comment by kocunop** [comment]
gettext(message)[[source]](https://docs.djangoproject.com/en/1.8/_modules/django/utils/translation/#gettext)[¶](https://docs.djangoproject.com/en/1.8/ref/utils/#django.utils.translation.gettext)
Translates message and returns it in a UTF-8 bytestring

ugettext(message)[[source]](https://docs.djangoproject.com/en/1.8/_modules/django/utils/translation/#ugettext)[¶](https://docs.djangoproject.com/en/1.8/ref/utils/#django.utils.translation.ugettext)
Translates message and returns it in a unicode string

I think it has to do with python 2.7 support. And will not work properly with django < 2.2

The last version to support Python 2.7 is Django 1.11 LTS. [source](https://www.djangoproject.com/download/)

**Pull request merged**
